Fixes01
durangoretro/durango_demos pull request #1
Opened 2022-08-20 13:56 UTC by emiliollbb

Correcciones del gurú 6502

2022-08-20 13:57 UTC, emiliollbb commented on pong.s
> -                        ; lo mismo de antes, no hay obligación de usar A en todas las cargas *** OK!
Aunque se vea un poco menos claro así, lo cambio y me voy acostumbrando a usar no sólo A

2022-08-20 13:59 UTC, emiliollbb commented on pong.s
> -    STY p2_horizontal_y	; *** pero me sigo liando un poco con lo de vertical/horizontal x/y
Vertical y Horizontal es porque cada jugador controla dos palas: una vertical en el lado izquierdo (p1) y otra arriba (p1). El jugador dos tiene otras dos palas, una en el lado derecho de la pantalla y la otra abajo.

2022-08-20 14:00 UTC, emiliollbb commented on pong.s
> -    STA CURRENT_COLOR	; *** si fill_screen respeta A (como indicado) no hace falta esta variable
Cambiado

2022-08-20 14:00 UTC, emiliollbb commented on pong.s
> -    STA CURRENT_COLOR
Uso A en el background de momento, a falta de revisar el fillScreen y ver si es más interesante hacerlo en X o Y

2022-08-20 14:01 UTC, emiliollbb commented on pong.s
> -;  puedes cargar un registro índice (ej. X) con 0 o 1 para seleccionar el jugador, usando direccionamiento indexado (ej. LDY p_vertical_x, X  ...que deja libre A para el color)
Cambiado

2022-08-20 14:01 UTC, emiliollbb commented on pong.s
> -    PHY					; *** si Y lo machacas a continuación, no es preciso salvarlo. A (color) y X (jugador) sí deben ser salvados.
Cuánta razón...

2022-08-20 14:05 UTC, emiliollbb commented on pong.s
> -    JSR _player1_up		; imagino que tocará A (y de todo), de lo contrario en CMOS es posible hacer un único LDA CONTROLLER_1 y sucesivos BIT #BUTTON...
La ventaja de hacerlo así, es que no hay que preocuparse de lo que hagan los procedimientos asociados a cada tecla

2022-08-20 14:06 UTC, emiliollbb commented on pong.s
> +	STA CURRENT_COLOR							; *** aquí se va a machacar A (el color), así que lo óptimo sería guardarlo en CURRENT_COLOR *aquí*... o tal vez en la pila
Lo pongo de momento así, para que siga funcionando, y pienso cómo hacerlo con la pila, porque el pull cae dentro de un bucle

2022-08-20 14:17 UTC, zuiko21 commented on pong.s
> -                        ; lo mismo de antes, no hay obligación de usar A en todas las cargas *** OK!
También puedes agrupar todas las escrituras de un mismo valor, por claridad

2022-08-20 14:17 UTC, zuiko21 commented on pong.s
> -    STY p2_horizontal_y	; *** pero me sigo liando un poco con lo de vertical/horizontal x/y
OK. Entonces es SchizoPong :-) :-) :-)

2022-08-20 14:22 UTC, zuiko21 commented on pong.s
> -    JSR _player1_up		; imagino que tocará A (y de todo), de lo contrario en CMOS es posible hacer un único LDA CONTROLLER_1 y sucesivos BIT #BUTTON...
Sí, en el caso que nos ocupa, no vale la pena. Pero tenlo en cuenta para futuras ocasiones...

2022-08-20 14:25 UTC, zuiko21 commented on pong.s
> +	STA CURRENT_COLOR							; *** aquí se va a machacar A (el color), así que lo óptimo sería guardarlo en CURRENT_COLOR *aquí*... o tal vez en la pila
No sé si esta conversación se refiere al código de arriba (_draw_square) o al de abajo (fill_screen)...

2022-08-20 14:29 UTC, zuiko21 commented on pong.s
> +    BPL loop
Ni idea de lo que estoy haciendo, pero si quieres que fill_screen sea genérica para todos los buffers, el truco BPL no nos vale. Lo suyo sería, tras el STX VMEM_POINTER+1, hacer un LDX que cargue el límite superior de alguna variable; entonces, tras el INC VMEM_POINTER+1 del final, hacer CPX VMEM_POINTER+1 y luego el BNE "clásico"

2022-08-20 14:30 UTC, zuiko21 commented on pong.s
> -    STA CURRENT_COLOR
No me entero bien...

2022-08-20 14:38 UTC, emiliollbb commented on pong.s
> -    STA CURRENT_COLOR
No lo.mites todavía. En.progreso

2022-08-20 14:39 UTC, emiliollbb commented on pong.s
> +	STA CURRENT_COLOR							; *** aquí se va a machacar A (el color), así que lo óptimo sería guardarlo en CURRENT_COLOR *aquí*... o tal vez en la pila
Al draw_square, no.mired todavia

2022-08-20 14:47 UTC, zuiko21 requested changes
Soy novato

2022-08-20 14:51 UTC, zuiko21 commented on pong.s
> +	STA CURRENT_COLOR							; *** aquí se va a machacar A (el color), así que lo óptimo sería guardarlo en CURRENT_COLOR *aquí*... o tal vez en la pila
empiezo a entender algo...
tal vez el problema sea que "tienes" que recalcular la anchura en bytes para todas y cada una de las líneas... un desperdicio.
mejor hacerlo al principio o, incluso, trabajar directamente con ese valor en bytes, no píxeles

2022-08-20 14:52 UTC, zuiko21 commented
Comment about _draw_square

2022-08-21 05:47 UTC, emiliollbb commented on pong.s
> +    BPL loop
Cómo tenía puesto un $80, y ya tenemos la genérica en la librería de C, pues he puesto la específica de la pantalla 03.

2022-08-21 05:48 UTC, emiliollbb commented
> Soy novato

Además de los comentarios específicos de una línea de código, se pueden poner genéricos, como éste tuyo, y esta respuesta

2022-08-21 07:08 UTC, emiliollbb commented on pong.s
>  ; Draw square
Este procedimiento, draw square, ya está listo

2022-08-21 13:20 UTC, emiliollbb commented on pong.s
> +	STA CURRENT_COLOR							; *** aquí se va a machacar A (el color), así que lo óptimo sería guardarlo en CURRENT_COLOR *aquí*... o tal vez en la pila
_draw_square arreglado

2022-08-21 13:21 UTC, emiliollbb commented on pong.s
> -    STA CURRENT_COLOR
Hecho.

2022-08-24 10:07 UTC, merged